### ISSUE TITLE
ModelViewer should be able to show mesh normals

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenDungeonKeeper#25]
ModelViewer should be able to show mesh normals. Not by default, nope. Let's hook up letter N for this.

**Comment by tonihele** [comment]
Implemented. Well, not on animating ones, but they are a totally different story, again. Animation doesn't alter the normals, so we'll have to see how it handles there... Most of the time could be ok..

**Comment by ufdada** [comment]
btw: you should be able to automaticly close an issue if you write something like `Fixes #8` in the commit message. See also: [Closing issues via commit messages - User Documentation](https://help.github.com/articles/closing-issues-via-commit-messages/). This should save some time ;)

**Comment by tonihele** [comment]
Thanks. I'm still learning the branching etc. At work and outside work it has just been CVS/SVN :)
