### ISSUE TITLE
Implement conversion for the game texts

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenDungeonKeeper#27]
Implement conversion for the game texts. As we at some point are required to complement these anyway. They should be converted to simple text files. Perhaps using extension ".dict". And creating a simple AssetLoader for them.

The file format could be:
id=string

The strings returned by the StrFile reader are escaped to be on one line. And the ID is actually a line number. For human readability, these should be written in order (by the id/line number).

AssetLoader should warn about duplicate keys.

**Comment by tonihele** [comment]
We should not distribute these, ever, so at some point we should figure out how to make out the locale info on these and set up or own translations to another file which would be merged at loading time etc. But for now, simple conversion will do.

**Comment by tonihele** [comment]
It is now done! Unfortunately again my GitHub skills... I'm not sure I did it the correct way. I merged the branch in NetBeans. It doesn't leave a trace. Maybe merge in GitHub or does it matter??

**Comment by ufdada** [comment]
I think the problem is that you merge your local branches instead of remote branches. (so git doesn't really know).

**Comment by tonihele** [comment]
That is true. Is it possible to merge the remote branches with Netbeans? Or should I just merge them in GitHub?

**Comment by ufdada** [comment]
I actually never tried it with netbeans. I merge them on github.

**Comment by ufdada** [comment]
Back to topic: Maybe the Language Key in "HKEY_CURRENT_USER\Software\Bullfrog Productions Ltd\Dungeon Keeper II" will be helpfull to figure the correct local.

**Comment by tonihele** [comment]
Could be, I have 9 as language setting there. Breaks the cross platforming however, and can JAVA read Windows registry?

Seems it can but not very pleasantly... http://stackoverflow.com/questions/62289/read-write-to-windows-registry-using-java.

There is in the code page file, MBtoUNI, after the char[4] header there is a 16-bit number. I wonder if it could be a locale of some sorts? I have 0 there. But same page file might be in use for many languages.

But maybe it doesn't matter now. The game would be by default in the language the user has the game installed. And we just append "texts_custom_en/fi/ge.dict" to it? Even Bullfrog didn't do a thorough job here, at least Polish version has many strings in English.
