### ISSUE TITLE
Implement Hero Gate [Front End] construction

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenDungeonKeeper#5]
A special main menu building. It comes in the Things data registry. Only possible to try to visually reverse engineer it from the Dungeon Keeper II itself. The building blocks (meshes) are named typically with 3dFrontEnd prefix.

This should be loaded in MapLoader. The main menu is an actual map. It should use the general stuff as far as possible. So that we could make use of camera sweep files (KSC), given that we ever understand them. But also the sounds. It is not actually music playing in the main menu. It is actually the soundtrack of the Hero Gate -> general stuff...

**Comment by ufdada** [comment]
I still wonder how they managed to get those little pieces of the mapselection to be interactive. I am afraid that there is still some kind of relevant logic hidden behind those unknown values. Here are some screenshots for reference. 

![shot0000](https://cloud.githubusercontent.com/assets/3787188/5823848/749dede8-a0e0-11e4-86e9-8c1fd8bb8f0f.jpg)
![shot0001](https://cloud.githubusercontent.com/assets/3787188/5823849/749f2dde-a0e0-11e4-97c9-0302eaf667d1.jpg)
![shot0003](https://cloud.githubusercontent.com/assets/3787188/5823851/74af9f16-a0e0-11e4-8feb-2bc42cfaf1dd.jpg)
![shot0004](https://cloud.githubusercontent.com/assets/3787188/5823850/74a52c7a-a0e0-11e4-8655-ed9b037c2c62.jpg)

The first thing to find out is what tileconstruction is really all about (if it is just some static summary of different models or somehow dynamicly put together). This is also useful for all bigger rooms (like the dungeon heart) and if we are lucky even for lava, water and tilesets (like claimed tiles).

**Comment by tonihele** [comment]
Wow, how did you manage to get that last image? Nice.

I think we have to hard code some of it as a special behavior in the Hero Gate [Front End] loading. Apply controls and meta data to the map peaces so we can interact with them through Nifty (the GUI we are currently using, or about to use). Shouldn't be too hard. And it still follows the idea of being very general (as this is an special item).

The map editor provides a good visualization of the data we can read from the maps. I recommend using the Pro version (http://keeper.lubiki.pl/html/dk2_tools_mapedit.php). It is what I used to reverse engineer the format.

Many of the meshes are already positioned, like the map selection, automatically it seems. Thank god for that. I haven't tried but it seems so, by using the ModelLoader.

![mapeditor](https://cloud.githubusercontent.com/assets/8344766/5824064/88bae97a-a0ea-11e4-88b2-6cd61f1e0c88.png)

**Comment by tonihele** [comment]
The MapLoader is indeed very crude. My first priority was just to get visual data. And I was hoping to find the common nominator. The flags help a bit... But that is all I got now for the tile construction.

**Comment by ufdada** [comment]
The last 3 screenshots were taken by directly loading the level per command line (in the dkII shortcut) with the option  <code>-level FrontEnd3DLevel</code>. 

This works for every level. So you don´t need to go to the menu all the time and you are able to load levels you are normally not allowed to ;).

**Comment by tonihele** [comment]
Great! I didn't even know that one.

**Comment by tonihele** [comment]
Ok, the front end tiles, I think it is just starting from the top left (dungeon heart on top) frontend1-9, then frontendl0-6. One model per one tile. There we have it, empty front end hero gate. Of course the items then to the correct slots.

**Comment by tonihele** [comment]
![frontend](https://cloud.githubusercontent.com/assets/8344766/6218627/c4a33c46-b628-11e4-9720-9d312751065c.png)

**Comment by ufdada** [comment]
holy crap, that looks awesome, did you place everything by hand?

**Comment by tonihele** [comment]
I increased the ambient lighting and am uploading a YouTube video of it currently. I have hooked the Main to open up these maps in just ambient lighting.

        AmbientLight al = new AmbientLight();
        al.setColor(ColorRGBA.White.multLocal(5f));
        rootNode.addLight(al);

 KwdFile kwdFile = new KwdFile((dkIIFolder), new File(dkIIFolder.concat("Data".concat(File.separator).concat("editor").concat(File.separator).concat("maps").concat(File.separator).concat("FrontEnd3DLevel.kwd"))));
rootNode.attachChild(new MapLoader().load(assetManager, kwdFile));

**Comment by tonihele** [comment]
I added a nice randomize effect on the animations, the original seems also to have scrambled the animations starts (?) but not randomize it every time. And the chains move so much slower in the original. I don't know why. But the randomizing is nice I think. Only that when it goes too slowly, they look like lagging which is not nice.

**Comment by tonihele** [comment]
http://youtu.be/oxnvUyG99kw

**Comment by ufdada** [comment]
:+1:

**Comment by tonihele** [comment]
I looked at some of the objects before but I just noticed that the chains are actually supposed to be played at 10 FPS. We construct everything as 30 FPS. Because it seems to be the default.
