### ISSUE TITLE
Figure out KCS files (camera sweep)

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenDungeonKeeper#8]
Figure out KCS files and convert them to JME motion paths. Really I think the only way to figure this one out is to contact an expert...

This would save us a lot of time and allow us to be more true to the original game.

**Comment by ufdada** [comment]
I would guess it´s some kind of frame (like in cam.setFrame(location, left, up, direction)) and a duration. Maybe that´s wrong, but that shouldn´t be to difficult to find out. Only needs a lot of time for playing arround with the values.

**Comment by tonihele** [comment]
I also first thought that they could be simple vectors which would tell these. But the DK II data is full of different kinds of gimmicks. Even if they are vectors, they could be in fixed point format. A bit tricky.

If you open up the Paths.WAD. Some of the file names have the length in seconds there. One entry might be one second.

Best guess at the moment is that the values actually form a bezier (http://en.wikipedia.org/wiki/B%C3%A9zier_curve). At least according to some experts... But it is a guess also....

One entry = one piece of bezier that is travelled in a second?

**Comment by ufdada** [comment]
Well that´s not a bad idea at all. There is a c++ implementation for ppsspp (the psp uses this in several games like loco roco): https://github.com/hrydgard/ppsspp/blob/master/GPU/Common/SplineCommon.cpp.

As they are easy to modify (and cut out) it´s probaly also used for terrain manipulation (with a lot less quads than used in psp).

**Comment by tonihele** [comment]
I've been talking to an expert. Not just anybody. Werkt, the guy who documented the model & texture formats and the map format reading stubs. He will provide us with the format documentation on KCS!

They are not beziers, it is much more simpler than that (which is nice). I already got the simple specs for the format. I'll push it in in few days.

**Comment by ufdada** [comment]
Wow, sounds really cool. Can´t wait to see it :).

**Comment by tonihele** [comment]
We don't have extensive amount of places to sweep the camera with (hopefully soon the start menu & dungeon heart just for showing off) :) And also you were the most right with your initial guess about the format.

**Comment by tonihele** [comment]
![camerapath](https://cloud.githubusercontent.com/assets/8344766/6358740/865c8ad8-bc76-11e4-9847-cb4b6d37d5f3.png)
I think the paths are somewhat ok. But the rotation too is off by the magical 90 degrees. Too bad I'm not a mathematical genius...

**Comment by ufdada** [comment]
Isn't the rotation of objects also off by 90?

**Comment by tonihele** [comment]
The very same... But I don't know how to implement it here. Rotating a quaternion again. It is basic math. But...

**Comment by ufdada** [comment]
I wouldn't focus too much on being completely right. Maybe implementing it on the first move brings up some new ideas :)

**Comment by tonihele** [comment]
Yeah, I'm worried about the scaling etc the most. Getting this to work would sort these things out at this early stage at least.

**Comment by tonihele** [comment]
I have this mess hooked up to the main, if you are curious to test etc.:
camNode.setEnabled(false); <-- Governs the camera

            // AP 23 = 16, 11 (level 1)
            final Vector3f start = new Vector3f(2.5f * 0.7f, 1f, 11.5f * 0.7f);  

// The KCS
            WadFile wadFile = new WadFile(new File(dkIIFolder.concat("Data".concat(File.separator).concat("Paths.WAD"))));
            File temp = File.createTempFile("herp", "derp");
            FileOutputStream fos = new FileOutputStream(temp);
//            wadFile.getFileData("EnginePath201.KCS").writeTo(fos);
            wadFile.getFileData("EnginePath251.KCS").writeTo(fos);
            fos.flush();
            fos.close();
            final KcsFile kcs = new KcsFile(temp);

            CameraNode camNode = new CameraNode("Motion cam", cam);
            camNode.setControlDir(ControlDirection.SpatialToCamera);
//            camNode.setEnabled(false);
            final MotionPath path = new MotionPath();
            path.setCycle(true);
            for (KcsEntry entry : kcs.getKcsEntries()) {
                Vector3f v = new Vector3f(entry.getPosition().x, entry.getPosition().z, entry.getPosition().y);
                path.addWayPoint(v.mult(0.7f).add(start));
            }
            path.setCurveTension(0.83f);
            path.enableDebugShape(assetManager, rootNode);

            final float fps = 15f;
            final MotionEvent cameraMotionControl = new MotionEvent(camNode, path) {
                @Override
                public void update(float tpf) {
                    super.update(tpf); //To change body of generated methods, choose Tools | Templates.

                    // Rotate
                    float duration = getCurrentValue();
                    int startIndex = getCurrentWayPoint();
                    int endIndex = startIndex + 1;
//                    getTime();
//                    setRotation(rotation);

                    Quaternion q1 = new Quaternion();
                    KcsEntry entry = kcs.getKcsEntries().get(startIndex);
                    q1.fromAxes(new Vector3f(entry.getLeft().x, entry.getLeft().z, entry.getLeft().y), new Vector3f(entry.getForward().x, entry.getForward().z, entry.getForward().y), new Vector3f(entry.getUp().x, entry.getUp().z, entry.getUp().y));

                    if (endIndex < kcs.getKcsEntries().size()) {
                        Quaternion q2 = new Quaternion();
                        entry = kcs.getKcsEntries().get(endIndex);
                        q2.fromAxes(new Vector3f(entry.getLeft().x, entry.getLeft().z, entry.getLeft().y), new Vector3f(entry.getForward().x, entry.getForward().z, entry.getForward().y), new Vector3f(entry.getUp().x, entry.getUp().z, entry.getUp().y));

                        q1.slerp(q2, duration);
                    }

                    Quaternion quat = new Quaternion();
                    quat.fromAngleAxis(FastMath.PI / 2, new Vector3f(1, 0, 0));
//                    q1.inverseLocal();

                    setRotation(q1);
                }
            };
            cameraMotionControl.setLoopMode(LoopMode.Loop);
            cameraMotionControl.setInitialDuration(kcs.getKcsEntries().size() / fps);
            cameraMotionControl.setLookAt(Vector3f.ZERO, Vector3f.ZERO);
            cameraMotionControl.setDirectionType(MotionEvent.Direction.Rotation);
            rootNode.attachChild(camNode);
            cameraMotionControl.play();

**Comment by tonihele** [comment]
I implemented the conversion. They are now converted to our own format, for convenience. And if we need to do something about the data (like before I switched the Y & Z axis), it can be done with ease at "design" time.

I also implemented these to a cinematic. To initiate such cinematic, just:

        Cinematic c = new Cinematic(assetManager, cam, new Point(3, 12), "EnginePath251", rootNode);
        stateManager.attach(c);
        c.play();

Also temporarily you can i.e. remove the rotation from the MapLoader and apply it to the rootNode instead. Or attach a node to the root node which you would apply the rotation.

**Comment by tonihele** [comment]
Later we can extend the cinematic to handle the wide screen triggers, as well as the play narrative triggers.

**Comment by tonihele** [comment]
There is still something that doesn't fit in quite right, but at least we now understand and process the KCSs, so in that scope this is truly done.

The camera rotation is not perfect in all situations, but I begin to implement it in real world events. This will make debuging easy.

Here is a quote from the original specs by George Gensure, about the rotation:

    The axis vectors are placed into a 3x3 rotation matrix with the following
    positioning for multiplication with the scene.
    
    forward[0] −left[0] −up[0]
    −forward[1] left[1] up[1]
    −forward[2] left[2] up[2]

**Comment by tonihele** [comment]
When the rotation is totally nailed, we can change our format to just have the matrix ready. Everything that keeps us from producing new objects (the camera path is really a dense path, not really optimized one) is a big plus. It is pre-production optimizing :) The GC can apparently cause games to run slow.
